
alter table public.job_requests
  drop constraint if exists job_requests_status_check;

alter table public.job_requests
  add constraint job_requests_status_check check (
    status in (
      'open',
      'accepted',
      'scheduled',
      'on_the_way',
      'in_progress',
      'pending_completion',
      'completed',
      'closed',
      'cancelled'
    )
  );

create table public.job_status_history (
  id bigint generated by default as identity primary key,
  job_request_id uuid not null references public.job_requests(id) on delete cascade,
  status text not null check (
    status in (
      'accepted',
      'scheduled',
      'on_the_way',
      'in_progress',
      'pending_completion',
      'completed'
    )
  ),
  updated_at timestamptz not null default now(),
  unique (job_request_id, status)
);

create index job_status_history_job_request_id_idx
  on public.job_status_history (job_request_id, updated_at);

alter table public.job_status_history enable row level security;
grant select on public.job_status_history to authenticated;

create policy "Customers can view their job status history"
  on public.job_status_history for select to authenticated
  using (
    exists (
      select 1
      from public.job_requests as job
      where job.id = job_status_history.job_request_id
        and job.customer_id = (select auth.uid())
    )
  );

create or replace function public.record_job_status_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status is distinct from old.status
    and new.status in (
      'accepted',
      'scheduled',
      'on_the_way',
      'in_progress',
      'pending_completion',
      'completed'
    ) then
    insert into public.job_status_history (job_request_id, status, updated_at)
    values (new.id, new.status, coalesce(new.updated_at, now()))
    on conflict (job_request_id, status) do nothing;
  end if;

  return new;
end;
$$;

drop trigger if exists job_requests_record_status_change on public.job_requests;
create trigger job_requests_record_status_change
  after update of status on public.job_requests
  for each row execute function public.record_job_status_change();

insert into public.job_status_history (job_request_id, status, updated_at)
select job.id, 'accepted', quote.updated_at
from public.job_requests as job
join public.job_quotes as quote on quote.job_request_id = job.id
where quote.status = 'accepted'
  and job.status in ('in_progress', 'completed')
on conflict (job_request_id, status) do nothing;

insert into public.job_status_history (job_request_id, status, updated_at)
select job.id, job.status, job.updated_at
from public.job_requests as job
where job.status in ('in_progress', 'completed')
on conflict (job_request_id, status) do nothing;

create or replace function public.respond_to_job_quote(
  p_quote_id uuid,
  p_accept boolean
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_request_id uuid;
  v_quote_status text;
  v_quote_created_at timestamptz;
  v_job_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select quote.job_request_id, quote.status, quote.created_at
  into v_job_request_id, v_quote_status, v_quote_created_at
  from public.job_quotes as quote
  join public.job_requests as job on job.id = quote.job_request_id
  where quote.id = p_quote_id
    and job.customer_id = auth.uid();

  if not found then
    raise exception 'Quote not found' using errcode = 'P0002';
  end if;

  select status into v_job_status
  from public.job_requests
  where id = v_job_request_id
  for update;

  if v_quote_status = 'awaiting_response'
    and now() > public.five_working_days_after(v_quote_created_at) then
    raise exception 'The five-working-day response period has expired';
  end if;

  if p_accept then
    if v_quote_status = 'accepted'
      and v_job_status in (
        'accepted',
        'scheduled',
        'on_the_way',
        'in_progress',
        'pending_completion',
        'completed'
      ) then
      return 'accepted';
    end if;

    if v_quote_status <> 'awaiting_response' or v_job_status <> 'open' then
      raise exception 'This quote can no longer be accepted';
    end if;

    update public.job_quotes
    set status = 'rejected'
    where job_request_id = v_job_request_id
      and id <> p_quote_id
      and status = 'awaiting_response';

    update public.job_quotes set status = 'accepted' where id = p_quote_id;
    update public.job_requests set status = 'accepted' where id = v_job_request_id;
    return 'accepted';
  end if;

  if v_quote_status <> 'awaiting_response' or v_job_status <> 'open' then
    raise exception 'This quote can no longer be declined';
  end if;

  update public.job_quotes set status = 'rejected' where id = p_quote_id;
  return 'rejected';
end;
$$;

drop function if exists public.get_business_active_jobs(uuid);
create function public.get_business_active_jobs(p_business_id uuid)
returns table (
  job_request_id uuid,
  quote_id uuid,
  title text,
  description text,
  category text,
  city text,
  suburb text,
  amount_cents integer,
  job_status text,
  accepted_at timestamptz,
  status_updated_at timestamptz,
  status_history jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.business_has_capability(p_business_id, 'service_marketplace') then
    raise exception 'Service Marketplace access required' using errcode = '42501';
  end if;

  return query
  select
    job.id::uuid,
    quote.id::uuid,
    job.title::text,
    job.description::text,
    job.category::text,
    job.city::text,
    job.suburb::text,
    quote.amount_cents::integer,
    job.status::text,
    coalesce(progress.accepted_at, quote.updated_at)::timestamptz,
    coalesce(progress.status_updated_at, job.updated_at)::timestamptz,
    coalesce(progress.status_history, '[]'::jsonb)::jsonb
  from public.job_quotes as quote
  join public.job_requests as job on job.id = quote.job_request_id
  left join lateral (
    select
      min(history.updated_at) filter (where history.status = 'accepted') as accepted_at,
      max(history.updated_at) as status_updated_at,
      jsonb_agg(
        jsonb_build_object(
          'status', history.status,
          'updated_at', history.updated_at
        )
        order by history.updated_at
      ) as status_history
    from public.job_status_history as history
    where history.job_request_id = job.id
  ) as progress on true
  where quote.business_id = p_business_id
    and quote.status = 'accepted'
    and job.status in (
      'accepted',
      'scheduled',
      'on_the_way',
      'in_progress',
      'pending_completion',
      'completed'
    )
  order by coalesce(progress.status_updated_at, job.updated_at) desc;
end;
$$;

create or replace function public.update_business_job_status(
  p_business_id uuid,
  p_job_request_id uuid,
  p_status text
)
returns table (
  job_status text,
  status_updated_at timestamptz,
  status_history jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_status text;
  v_expected_status text;
begin
  if not public.business_has_capability(p_business_id, 'service_marketplace') then
    raise exception 'Service Marketplace access required' using errcode = '42501';
  end if;

  select job.status
  into v_current_status
  from public.job_requests as job
  where job.id = p_job_request_id
    and exists (
      select 1
      from public.job_quotes as quote
      where quote.job_request_id = job.id
        and quote.business_id = p_business_id
        and quote.status = 'accepted'
    )
  for update;

  if not found then
    raise exception 'Active job not found' using errcode = 'P0002';
  end if;

  v_expected_status := case v_current_status
    when 'accepted' then 'scheduled'
    when 'scheduled' then 'on_the_way'
    when 'on_the_way' then 'in_progress'
    when 'in_progress' then 'pending_completion'
    else null
  end;

  if v_expected_status is null or p_status is distinct from v_expected_status then
    raise exception 'Invalid job status transition from % to %',
      v_current_status,
      coalesce(p_status, 'null')
      using errcode = '22023';
  end if;

  update public.job_requests
  set status = p_status
  where id = p_job_request_id;

  return query
  select
    job.status::text,
    job.updated_at::timestamptz,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'status', history.status,
            'updated_at', history.updated_at
          )
          order by history.updated_at
        )
        from public.job_status_history as history
        where history.job_request_id = job.id
      ),
      '[]'::jsonb
    )
  from public.job_requests as job
  where job.id = p_job_request_id;
end;
$$;

create or replace function public.confirm_job_completion(p_job_request_id uuid)
returns table (
  job_status text,
  status_updated_at timestamptz,
  status_history jsonb
)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_current_status text;
begin
  if auth.uid() is null then
    raise exception 'Authentication required' using errcode = '42501';
  end if;

  select job.status
  into v_current_status
  from public.job_requests as job
  where job.id = p_job_request_id
    and job.customer_id = auth.uid()
  for update;

  if not found then
    raise exception 'Job not found' using errcode = 'P0002';
  end if;

  if v_current_status <> 'pending_completion' then
    raise exception 'This job is not awaiting completion confirmation'
      using errcode = '22023';
  end if;

  update public.job_requests
  set status = 'completed'
  where id = p_job_request_id;

  return query
  select
    job.status::text,
    job.updated_at::timestamptz,
    coalesce(
      (
        select jsonb_agg(
          jsonb_build_object(
            'status', history.status,
            'updated_at', history.updated_at
          )
          order by history.updated_at
        )
        from public.job_status_history as history
        where history.job_request_id = job.id
      ),
      '[]'::jsonb
    )
  from public.job_requests as job
  where job.id = p_job_request_id;
end;
$$;

revoke all on function public.complete_business_job(uuid, uuid) from public;
revoke execute on function public.complete_business_job(uuid, uuid) from authenticated;
revoke all on function public.get_business_active_jobs(uuid) from public;
revoke all on function public.update_business_job_status(uuid, uuid, text) from public;
revoke all on function public.confirm_job_completion(uuid) from public;

grant execute on function public.get_business_active_jobs(uuid) to authenticated;
grant execute on function public.update_business_job_status(uuid, uuid, text) to authenticated;
grant execute on function public.confirm_job_completion(uuid) to authenticated;
