create table public.customer_notifications (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references auth.users(id) on delete cascade,
  notification_type text not null check (
    notification_type in (
      'new_quote',
      'quote_withdrawn',
      'job_completed'
    )
  ),
  title text not null,
  message text not null,
  destination text not null,
  related_job_request_id uuid references public.job_requests(id) on delete set null,
  related_quote_id uuid references public.job_quotes(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index customer_notifications_customer_created_idx
  on public.customer_notifications (customer_id, created_at desc);

alter table public.customer_notifications enable row level security;
grant select on public.customer_notifications to authenticated;
grant update (read_at) on public.customer_notifications to authenticated;

create policy "Customers can view their own notifications"
  on public.customer_notifications for select to authenticated
  using (customer_id = (select auth.uid()));

create policy "Customers can mark their own notifications as read"
  on public.customer_notifications for update to authenticated
  using (customer_id = (select auth.uid()))
  with check (customer_id = (select auth.uid()));

  create or replace function public.notify_customer_about_new_quote()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer_id uuid;
  v_job_title text;
  v_business_name text;
begin
  select job.customer_id, job.title
    into v_customer_id, v_job_title
  from public.job_requests as job
  where job.id = new.job_request_id;

  select business.business_name
    into v_business_name
  from public.businesses as business
  where business.id = new.business_id;

  insert into public.customer_notifications (
    customer_id,
    notification_type,
    title,
    message,
    destination,
    related_job_request_id,
    related_quote_id
  )
  values (
    v_customer_id,
    'new_quote',
    'New quote received',
    coalesce(v_business_name, 'A provider') || ' sent a quote on ' ||
      coalesce(v_job_title, 'your job') || '.',
    '/jobs',
    new.job_request_id,
    new.id
  );

  return new;
end;
$$;

create trigger job_quotes_notify_customer_new_quote
  after insert on public.job_quotes
  for each row execute function public.notify_customer_about_new_quote();

create or replace function public.notify_customer_about_quote_withdrawal()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_customer_id uuid;
  v_job_title text;
  v_business_name text;
begin
  if old.status is not distinct from new.status or new.status <> 'withdrawn' then
    return new;
  end if;

  select job.customer_id, job.title
    into v_customer_id, v_job_title
  from public.job_requests as job
  where job.id = new.job_request_id;

  select business.business_name
    into v_business_name
  from public.businesses as business
  where business.id = new.business_id;

  insert into public.customer_notifications (
    customer_id,
    notification_type,
    title,
    message,
    destination,
    related_job_request_id,
    related_quote_id
  )
  values (
    v_customer_id,
    'quote_withdrawn',
    'Quote withdrawn',
    coalesce(v_business_name, 'A provider') || ' withdrew their quote on ' ||
      coalesce(v_job_title, 'your job') || '.',
    '/jobs',
    new.job_request_id,
    new.id
  );

  return new;
end;
$$;

create trigger job_quotes_notify_customer_withdrawal
  after update of status on public.job_quotes
  for each row execute function public.notify_customer_about_quote_withdrawal();

create or replace function public.notify_customer_about_scheduled_job()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is not distinct from new.status or new.status <> 'scheduled' then
    return new;
  end if;

  insert into public.customer_notifications (
    customer_id, notification_type, title, message, destination, related_job_request_id
  )
  values (
    new.customer_id,
    'job_scheduled',
    'Job scheduled',
    coalesce(new.title, 'Your job') || ' has been scheduled.',
    '/jobs',
    new.id
  );

  return new;
end;
$$;

create trigger job_requests_notify_customer_scheduled
  after update of status on public.job_requests
  for each row execute function public.notify_customer_about_scheduled_job();

create or replace function public.notify_customer_about_on_the_way_job()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is not distinct from new.status or new.status <> 'on_the_way' then
    return new;
  end if;

  insert into public.customer_notifications (
    customer_id, notification_type, title, message, destination, related_job_request_id
  )
  values (
    new.customer_id,
    'on_the_way',
    'Job is on the way',
    coalesce(new.title, 'Your job') || ' is on the way.',
    '/jobs',
    new.id
  );

  return new;
end;
$$;

create trigger job_requests_notify_customer_on_the_way
  after update of status on public.job_requests
  for each row execute function public.notify_customer_about_on_the_way_job();

create or replace function public.notify_customer_about_in_progress_job()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is not distinct from new.status or new.status <> 'in_progress' then
    return new;
  end if;

  insert into public.customer_notifications (
    customer_id, notification_type, title, message, destination, related_job_request_id
  )
  values (
    new.customer_id,
    'in_progress',
    'Job is in progress',
    coalesce(new.title, 'Your job') || ' is cuurently in progress.',
    '/jobs',
    new.id
  );

  return new;
end;
$$;

create trigger job_requests_notify_customer_in_progress
  after update of status on public.job_requests
  for each row execute function public.notify_customer_about_in_progress_job();

create or replace function public.notify_customer_about_completed_job()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is not distinct from new.status or new.status <> 'completed' then
    return new;
  end if;

  insert into public.customer_notifications (
    customer_id,
    notification_type,
    title,
    message,
    destination,
    related_job_request_id
  )
  values (
    new.customer_id,
    'job_completed',
    'Job marked complete',
    coalesce(new.title, 'Your job') || ' has been marked complete.',
    '/jobs',
    new.id
  );

  return new;
end;
$$;

create trigger job_requests_notify_customer_completed
  after update of status on public.job_requests
  for each row execute function public.notify_customer_about_completed_job();

drop function if exists public.get_customer_notifications(uuid, integer);
create function public.get_customer_notifications(
  p_customer_id uuid,
  p_limit integer default 20
)
returns table (
  notification_id bigint,
  notification_type text,
  title text,
  message text,
  destination text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if p_customer_id <> auth.uid() then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  return query
  select
    notification.id,
    notification.notification_type,
    notification.title,
    notification.message,
    notification.destination,
    notification.created_at,
    notification.read_at
  from public.customer_notifications as notification
  where notification.customer_id = p_customer_id
  order by notification.created_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
end;
$$;

drop function if exists public.mark_customer_notifications_read(uuid, bigint[]);
create function public.mark_customer_notifications_read(
  p_customer_id uuid,
  p_notification_ids bigint[] default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_updated_count integer;
begin
  if p_customer_id <> auth.uid() then
    raise exception 'Not authorized' using errcode = '42501';
  end if;

  update public.customer_notifications as notification
  set read_at = now()
  where notification.customer_id = p_customer_id
    and notification.read_at is null
    and (
      p_notification_ids is null
      or notification.id = any(p_notification_ids)
    );

  get diagnostics v_updated_count = row_count;
  return v_updated_count;
end;
$$;

revoke all on function public.get_customer_notifications(uuid, integer) from public;
revoke all on function public.mark_customer_notifications_read(uuid, bigint[]) from public;

grant execute on function public.get_customer_notifications(uuid, integer) to authenticated;
grant execute on function public.mark_customer_notifications_read(uuid, bigint[]) to authenticated;

alter publication supabase_realtime add table public.customer_notifications;