
create table public.loyalty_activity (
  id bigint generated by default as identity primary key,
  loyalty_record_id uuid not null
    references public.customer_loyalty_records(id) on delete cascade,
  activity_type text not null,
  amount numeric(12, 2),
  created_at timestamptz not null default now(),
  constraint loyalty_activity_activity_type_check check (
    activity_type in (
      'progress_added',
      'reward_earned',
      'reward_redeemed'
    )
  ),
  constraint loyalty_activity_amount_check check (
    (
      activity_type = 'progress_added'
      and amount is not null
      and amount > 0
    )
    or (
      activity_type in ('reward_earned', 'reward_redeemed')
      and amount is null
    )
  )
);

create index loyalty_activity_record_created_idx
  on public.loyalty_activity (loyalty_record_id, created_at);

alter table public.loyalty_activity enable row level security;

revoke all on table public.loyalty_activity from anon, authenticated;
grant select on public.loyalty_activity to authenticated;

create policy "Customers can view their own loyalty activity"
  on public.loyalty_activity for select to authenticated
  using (
    exists (
      select 1
      from public.customer_loyalty_records as record
      where record.id = loyalty_record_id
        and record.customer_id = (select auth.uid())
    )
  );

comment on table public.loyalty_activity is
  'Append-only history for loyalty progress and reward lifecycle events.';

comment on column public.loyalty_activity.amount is
  'Progress amount only. Its unit is determined by the loyalty programme type.';
