
create table public.business_notifications (
  id bigint generated by default as identity primary key,
  business_id uuid not null references public.businesses(id) on delete cascade,
  notification_type text not null check (
    notification_type in (
      'new_lead',
      'quote_approved',
      'quote_updated',
      'job_completed'
    )
  ),
  title text not null,
  message text not null,
  destination text not null,
  related_job_request_id uuid references public.job_requests(id) on delete set null,
  related_quote_id uuid references public.job_quotes(id) on delete set null,
  created_at timestamptz not null default now(),
  read_at timestamptz
);

create index business_notifications_business_created_idx
  on public.business_notifications (business_id, created_at desc);

alter table public.business_notifications enable row level security;
grant select on public.business_notifications to authenticated;
grant update (read_at) on public.business_notifications to authenticated;

create policy "Business members can view notifications"
  on public.business_notifications for select to authenticated
  using (public.is_business_member(business_id));

create policy "Business members can mark notifications as read"
  on public.business_notifications for update to authenticated
  using (public.is_business_member(business_id))
  with check (public.is_business_member(business_id));

create or replace function public.notify_businesses_about_new_lead()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.status <> 'open' then
    return new;
  end if;

  insert into public.business_notifications (
    business_id,
    notification_type,
    title,
    message,
    destination,
    related_job_request_id
  )
  select distinct
    category.business_id,
    'new_lead',
    'New lead available',
    new.title || ' in ' || coalesce(new.suburb || ', ', '') || new.city,
    '/business/services',
    new.id
  from public.business_service_categories as category
  join public.business_service_areas as area
    on area.business_id = category.business_id
  join public.business_capabilities as capability
    on capability.business_id = category.business_id
  where capability.service_marketplace_enabled
    and lower(trim(category.service_category)) = lower(trim(new.category))
    and lower(trim(area.service_area)) in (
      lower(trim(new.suburb)),
      lower(trim(new.city))
    );

  return new;
end;
$$;

create trigger job_requests_notify_new_lead
  after insert on public.job_requests
  for each row execute function public.notify_businesses_about_new_lead();

create or replace function public.notify_business_about_quote_update()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_job_title text;
begin
  if old.status is not distinct from new.status then
    return new;
  end if;

  select job.title into v_job_title
  from public.job_requests as job
  where job.id = new.job_request_id;

  if new.status = 'accepted' then
    insert into public.business_notifications (
      business_id,
      notification_type,
      title,
      message,
      destination,
      related_job_request_id,
      related_quote_id
    )
    values (
      new.business_id,
      'quote_approved',
      'Quote approved',
      coalesce(v_job_title, 'Your quote') || ' moved from Quotes to Jobs.',
      '/business/services?tab=jobs',
      new.job_request_id,
      new.id
    );
  else
    insert into public.business_notifications (
      business_id,
      notification_type,
      title,
      message,
      destination,
      related_job_request_id,
      related_quote_id
    )
    values (
      new.business_id,
      'quote_updated',
      'Quote updated',
      coalesce(v_job_title, 'Your quote') || ' is now ' ||
        replace(new.status, '_', ' ') || '.',
      '/business/services?tab=quotes',
      new.job_request_id,
      new.id
    );
  end if;

  return new;
end;
$$;

create trigger job_quotes_notify_status_update
  after update of status on public.job_quotes
  for each row execute function public.notify_business_about_quote_update();

create or replace function public.notify_business_about_completed_job()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if old.status is not distinct from new.status or new.status <> 'completed' then
    return new;
  end if;

  insert into public.business_notifications (
    business_id,
    notification_type,
    title,
    message,
    destination,
    related_job_request_id,
    related_quote_id
  )
  select
    quote.business_id,
    'job_completed',
    'Job completed',
    new.title || ' moved from Jobs to Job History.',
    '/business/services?tab=history',
    new.id,
    quote.id
  from public.job_quotes as quote
  where quote.job_request_id = new.id
    and quote.status = 'accepted';

  return new;
end;
$$;

create trigger job_requests_notify_completed_job
  after update of status on public.job_requests
  for each row execute function public.notify_business_about_completed_job();

drop function if exists public.get_business_notifications(uuid, integer);
create function public.get_business_notifications(
  p_business_id uuid,
  p_limit integer default 20
)
returns table (
  notification_id bigint,
  notification_type text,
  title text,
  message text,
  destination text,
  created_at timestamptz,
  read_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.is_business_member(p_business_id) then
    raise exception 'Business membership required' using errcode = '42501';
  end if;

  return query
  select
    notification.id,
    notification.notification_type,
    notification.title,
    notification.message,
    notification.destination,
    notification.created_at,
    notification.read_at
  from public.business_notifications as notification
  where notification.business_id = p_business_id
  order by notification.created_at desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
end;
$$;

drop function if exists public.mark_business_notifications_read(uuid, bigint[]);
create function public.mark_business_notifications_read(
  p_business_id uuid,
  p_notification_ids bigint[] default null
)
returns integer
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_updated_count integer;
begin
  if not public.is_business_member(p_business_id) then
    raise exception 'Business membership required' using errcode = '42501';
  end if;

  update public.business_notifications as notification
  set read_at = now()
  where notification.business_id = p_business_id
    and notification.read_at is null
    and (
      p_notification_ids is null
      or notification.id = any(p_notification_ids)
    );

  get diagnostics v_updated_count = row_count;
  return v_updated_count;
end;
$$;

drop function if exists public.get_business_quotes(uuid);
create function public.get_business_quotes(p_business_id uuid)
returns table (
  quote_id uuid,
  job_request_id uuid,
  title text,
  description text,
  category text,
  city text,
  suburb text,
  price_type text,
  amount_cents integer,
  availability_date date,
  arrival_window text,
  included_work text,
  conditions text,
  expected_duration text,
  message text,
  quote_status text,
  response_deadline timestamptz,
  created_at timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.business_has_capability(p_business_id, 'service_marketplace') then
    raise exception 'Service Marketplace access required' using errcode = '42501';
  end if;

  return query
  select
    quote.id::uuid,
    job.id::uuid,
    job.title::text,
    job.description::text,
    job.category::text,
    job.city::text,
    job.suburb::text,
    quote.price_type::text,
    quote.amount_cents::integer,
    quote.availability_date::date,
    quote.arrival_window::text,
    quote.included_work::text,
    quote.conditions::text,
    quote.expected_duration::text,
    quote.message::text,
    case
      when quote.status = 'awaiting_response'
        and job.status in ('closed', 'cancelled') then 'request_withdrawn'
      when quote.status = 'awaiting_response'
        and now() > public.five_working_days_after(quote.created_at) then 'expired'
      when quote.status = 'rejected' then 'declined'
      else quote.status
    end::text,
    public.five_working_days_after(quote.created_at)::timestamptz,
    quote.created_at::timestamptz
  from public.job_quotes as quote
  join public.job_requests as job on job.id = quote.job_request_id
  where quote.business_id = p_business_id
    and quote.status <> 'accepted'
  order by quote.created_at desc;
end;
$$;

drop function if exists public.get_business_active_jobs(uuid);
create function public.get_business_active_jobs(p_business_id uuid)
returns table (
  job_request_id uuid,
  quote_id uuid,
  title text,
  description text,
  category text,
  city text,
  suburb text,
  amount_cents integer,
  job_status text,
  accepted_at timestamptz,
  status_updated_at timestamptz,
  status_history jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.business_has_capability(p_business_id, 'service_marketplace') then
    raise exception 'Service Marketplace access required' using errcode = '42501';
  end if;

  return query
  select
    job.id::uuid,
    quote.id::uuid,
    job.title::text,
    job.description::text,
    job.category::text,
    job.city::text,
    job.suburb::text,
    quote.amount_cents::integer,
    job.status::text,
    coalesce(progress.accepted_at, quote.updated_at)::timestamptz,
    coalesce(progress.status_updated_at, job.updated_at)::timestamptz,
    coalesce(progress.status_history, '[]'::jsonb)::jsonb
  from public.job_quotes as quote
  join public.job_requests as job on job.id = quote.job_request_id
  left join lateral (
    select
      min(history.updated_at) filter (where history.status = 'accepted') as accepted_at,
      max(history.updated_at) as status_updated_at,
      jsonb_agg(
        jsonb_build_object(
          'status', history.status,
          'updated_at', history.updated_at
        )
        order by history.updated_at
      ) as status_history
    from public.job_status_history as history
    where history.job_request_id = job.id
  ) as progress on true
  where quote.business_id = p_business_id
    and quote.status = 'accepted'
    and job.status in (
      'accepted',
      'scheduled',
      'on_the_way',
      'in_progress',
      'pending_completion'
    )
  order by coalesce(progress.status_updated_at, job.updated_at) desc;
end;
$$;

drop function if exists public.get_business_job_history(uuid);
create function public.get_business_job_history(p_business_id uuid)
returns table (
  job_request_id uuid,
  quote_id uuid,
  title text,
  description text,
  category text,
  city text,
  suburb text,
  amount_cents integer,
  job_status text,
  accepted_at timestamptz,
  status_updated_at timestamptz,
  status_history jsonb
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not public.business_has_capability(p_business_id, 'service_marketplace') then
    raise exception 'Service Marketplace access required' using errcode = '42501';
  end if;

  return query
  select
    job.id::uuid,
    quote.id::uuid,
    job.title::text,
    job.description::text,
    job.category::text,
    job.city::text,
    job.suburb::text,
    quote.amount_cents::integer,
    job.status::text,
    coalesce(progress.accepted_at, quote.updated_at)::timestamptz,
    coalesce(progress.status_updated_at, job.updated_at)::timestamptz,
    coalesce(progress.status_history, '[]'::jsonb)::jsonb
  from public.job_quotes as quote
  join public.job_requests as job on job.id = quote.job_request_id
  left join lateral (
    select
      min(history.updated_at) filter (where history.status = 'accepted') as accepted_at,
      max(history.updated_at) as status_updated_at,
      jsonb_agg(
        jsonb_build_object(
          'status', history.status,
          'updated_at', history.updated_at
        )
        order by history.updated_at
      ) as status_history
    from public.job_status_history as history
    where history.job_request_id = job.id
  ) as progress on true
  where quote.business_id = p_business_id
    and quote.status = 'accepted'
    and job.status = 'completed'
  order by coalesce(progress.status_updated_at, job.updated_at) desc;
end;
$$;

revoke all on function public.get_business_notifications(uuid, integer) from public;
revoke all on function public.mark_business_notifications_read(uuid, bigint[]) from public;
revoke all on function public.get_business_quotes(uuid) from public;
revoke all on function public.get_business_active_jobs(uuid) from public;
revoke all on function public.get_business_job_history(uuid) from public;

grant execute on function public.get_business_notifications(uuid, integer) to authenticated;
grant execute on function public.mark_business_notifications_read(uuid, bigint[]) to authenticated;
grant execute on function public.get_business_quotes(uuid) to authenticated;
grant execute on function public.get_business_active_jobs(uuid) to authenticated;
grant execute on function public.get_business_job_history(uuid) to authenticated;

alter publication supabase_realtime add table public.business_notifications;
